from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime
from enum import Enum


class EventType(Enum):
    """Strongly typed event categories — prevents typo-based bugs."""
    MARKET = 'MARKET'
    SIGNAL = 'SIGNAL'
    ORDER  = 'ORDER'
    FILL   = 'FILL'


class SignalType(Enum):
    """Constrained signal vocabulary. Prevents invalid signal_type strings."""
    LONG  = 'LONG'
    SHORT = 'SHORT'
    EXIT  = 'EXIT'


class OrderType(Enum):
    """Order execution type."""
    MKT = 'MKT'
    LMT = 'LMT'


class Direction(Enum):
    """Trade direction."""
    BUY  = 'BUY'
    SELL = 'SELL'


class Event:
    """
    Base class for all events in the event-driven trading system.
    """
    pass


@dataclass(frozen=True)
class MarketEvent(Event):
    """
    Represents the receipt of a new market price update (bar or tick).
    Consumed by the Strategy module to calculate indicators and generate signals.
    
    frozen=True makes instances immutable and hashable — a market bar should
    never be mutated after creation.
    """
    timestamp: datetime
    symbol: str
    open_price: float
    high_price: float
    low_price: float
    close_price: float
    volume: int
    type: EventType = field(default=EventType.MARKET, init=False, repr=False)


@dataclass(frozen=True)
class SignalEvent(Event):
    """
    Represents a trading recommendation generated by a Strategy module.
    Consumed by the Portfolio & Risk Management module to check constraints and size positions.
    """
    symbol: str
    timestamp: datetime
    signal_type: str  # 'LONG', 'SHORT', or 'EXIT'
    strength: float   # Signal strength/confidence factor between 0.0 and 1.0
    type: EventType = field(default=EventType.SIGNAL, init=False, repr=False)

    def __post_init__(self) -> None:
        # Validate strength is bounded
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"Signal strength must be in [0.0, 1.0], got {self.strength}")


@dataclass(frozen=True)
class OrderEvent(Event):
    """
    Represents a verified, sized order ready to be routed to a brokerage.
    Generated by the Portfolio/Risk modules and consumed by the Execution Handler.
    """
    symbol: str
    order_type: str  # 'MKT' (Market) or 'LMT' (Limit)
    quantity: int
    direction: str   # 'BUY' or 'SELL'
    price: Optional[float] = None  # Price target (only required for Limit orders)
    type: EventType = field(default=EventType.ORDER, init=False, repr=False)


@dataclass(frozen=True)
class FillEvent(Event):
    """
    Represents the execution report of an order returned from a brokerage/exchange.
    Contains the exact transaction price, quantities, commissions, and simulated slippage.
    """
    symbol: str
    timestamp: datetime
    quantity: int
    direction: str   # 'BUY' or 'SELL'
    fill_price: float
    commission: float
    slippage: float = 0.0
    type: EventType = field(default=EventType.FILL, init=False, repr=False)
